### PR TITLE
Add new options remove_new_unused_deps and remove_unused_kernel

### LINKED ISSUE #106: Support Remove-New-Unused-Dependencies
According to the ubuntu docs there is a new feature since 16.04 which allows to remove unused dependencies caused by the upgrade.

https://help.ubuntu.com/community/RemoveOldKernels#Configure_Unattended_Upgrades_to_Remove_Unneeded_Kernels_Automatically

That would be very welcome.

### PR DESCRIPTION
**Pull request by gfa**
In unattended_upgrades > 2.5 is possible to configure unattended
upgrades to remove unused kernel packages and remove new unused
dependencies. This commit exposes this functionality to the puppet
module without changing the default.

If the new values are not set, nothing changes.

#### Pull Request (PR) description
This PR adds functionality to the module to manage the options 
- Unattended-Upgrade::Remove-New-Unused-Dependencies
- Unattended-Upgrade::Remove-Unused-Kernel-Packages

#### This Pull Request (PR) fixes the following issues
Fixes #106

### CODE REVIEW

**Comment by gfa** [comment]
> this looks pretty good so far

It didn't support the case of setting false to any of them, now it does (I amended the commit instead of a new commit because I like clean git history)

**Comment by igalic** [comment]
> It didn't support the case of setting false to any of them, now it does

can you please add a test for the false case, too

**Comment by gfa** [comment]
> > It didn't support the case of setting false to any of them, now it does
> 
> can you please add a test for the false case, too

@igalic commit 65fa65b  tests the existence of the entries the setting is configured (either true or false) and the non-existence of the entries when the entries are not defined ('undef', the default)

**Comment by igalic** [comment]
yes, but, please explicitly check the false case, because `nil` / `undef` is "falsey"

this is really just to future-proof free code (against accidental optimisation)

**Comment by gfa** [comment]
> yes, but, please explicitly check the false case, because `nil` / `undef` is "falsey"
> 
> this is really just to future-proof free code (against accidental optimisation)

done in f86b3ed

**Pull request merged**
