### PR TITLE
Add variable manage_package, manage_aptconf

### PR DESCRIPTION
**Pull request by Slm0n87**
- for external management of 'apt' ressources
- allows staging that module independent from module 'apt' in hiera

### CODE REVIEW

**Comment by daenney** [comment]
What's the point of using this module but not writing out the necessary apt configuration to do anything?

**Comment by jyaworski** [comment]
I'm inclined to agree with @daenney

**Comment by Slm0n87** [comment]
Hi, I had an issue with staging in puppet, to be able to make one single puppet-run.  
But finally I solved it by using this module within the same stage as the "apt" module  :)

So ths request can be closed

**Comment by daenney** [comment]
Oh. If you mean run stages in puppet, like the "stage" type you're going to be in for a world of hurt as most module don't account for it at all. The community has largely moved away from them because it causes more problems than it solves.

**Pull request closed without merging**
