### PR TITLE
Add support for Debian 11

### LINKED ISSUE #187: Debian 11 changes name of security suite
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: Debian 11 AKA bullseye
- Module version:

## What behaviour did you expect instead

Debian 11 should get these origins:

```
            'origin=Debian,codename=${distro_codename},label=Debian',
            'origin=Debian,codename=${distro_codename}-security,label=Debian-Security',
```

from `apt policy`:
```
 500 http://security.debian.org bullseye-security/main amd64 Packages
     release o=Debian,a=testing-security,n=bullseye-security,l=Debian-Security,c=main,b=amd64
     origin security.debian.org
```

Also see the Debian 11 release notes:
https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#security-archive

### PR DESCRIPTION
**Pull request by sboyd-m**
I believe this will work.

Closes #187

### CODE REVIEW

**Review by smortex — CHANGES_REQUESTED** [review]
This seem to unexpectedly change the behavior for Debian Buster.

Please update your code to keep the original behavior in place (unless it was broken?)

**Review by bastelfreak — COMMENTED** [review]
please also add Debian 11 to the metadata.json

**Comment by sboyd-m** [comment]
@smortex Not sure what adjustments you are referring to. In glancing at the code, and some old commits for adding new OSes, the changes I made seemed to be correct. It looks like this module has default origins on Debian only for the current release, and older releases get security origins by default. Buster is now an older release, as of a few weeks ago. Bullseye is `stable`, and buster is `oldstable`. I'm happy to just change it back of course, but the code as I see it ought to be the way it is in the PR.

**Comment by sboyd-m** [comment]
Should be good then.

Also just a side note, there are more references to old OS in other_debians_spec. Since you just cleaned stuff out in the other PRs, I figured I would let you know. I don't want to bother in this PR, since it's slightly unrelated.

**Review by smortex — APPROVED** [review]
LGTM!

**Comment by smortex** [comment]
> Also just a side note, there are more references to old OS in other_debians_spec. Since you just cleaned stuff out in the other PRs, I figured I would let you know. I don't want to bother in this PR, since it's slightly unrelated.

There is no strong policy here, when we "drop support", we stop making sure everything works and we are able to nuke legacy code.  This rarely happen at the same time, so next major release which "drop support" will in fact probably work as well for legacy releases, but removing the corresponding code is a following move.

If you want to assist in this, feel free to send more PRs :smiley: 

Thanks!

**Pull request merged**
