### PR TITLE
Add tags to metadata.json

### PR DESCRIPTION
**Pull request by petems**
* Forge search for unattended-upgrades doesn't 
show the VoxPup module
* Adding tags to increase SEO

### CODE REVIEW

**Comment by petems** [comment]
Current Google result for "unattended-upgrades puppet"

screenshot 2017-07-06 21 26 18

This should fix that :)

**Comment by bastelfreak** [comment]
thanks!

**Comment by bastelfreak** [comment]
ohhh rspec....

**Comment by bastelfreak** [comment]
@petems can you rebase here?

**Comment by petems** [comment]
@bastelfreak done! 😄

**Pull request merged**
